# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="gateway_transaction_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="verify_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="card_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
