# Generated by Django 5.2.10 on 2026-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("terms", "Terms"),
                            ("privacy", "Privacy"),
                            ("issuer_responsibility", "Issuer Responsibility"),
                            ("acceptable_use", "Acceptable Use"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("title_fa", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("body_fa", models.TextField()),
                ("body_en", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(default="Govahi", max_length=80)),
                ("display_name_fa", models.CharField(default="گواهی", max_length=80)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("default_locale", models.CharField(default="fa", max_length=8)),
                ("payment_bitpay_enabled", models.BooleanField(default=False)),
                ("bitpay_api_key", models.CharField(blank=True, max_length=200)),
                ("bitpay_callback_url", models.URLField(blank=True)),
                ("payment_zibal_enabled", models.BooleanField(default=False)),
                ("zibal_merchant_id", models.CharField(blank=True, max_length=200)),
                ("zibal_callback_url", models.URLField(blank=True)),
                ("trial_days", models.PositiveSmallIntegerField(default=14)),
                ("trial_certificate_limit", models.PositiveIntegerField(default=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "platform settings",
            },
        ),
    ]
