# Generated by Django 5.2.10 on 2026-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=120)),
                ("size", models.PositiveIntegerField()),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("storage_key", models.CharField(max_length=400, unique=True)),
                ("storage_provider", models.CharField(default="local", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
