export const designTokens = {
  color: {
    brand: {
      primary: "#38bdf8",
      primaryLight: "#7dd3fc",
      primaryDark: "#0284c7",
      secondary: "#22d3ee",
      accent: "#a78bfa",
    },
    background: {
      default: "#0a0f1a",
      surface: "#111827",
      elevated: "#1a2332",
      overlay: "rgba(2, 6, 23, 0.76)",
    },
    text: {
      primary: "#f1f5f9",
      secondary: "#94a3b8",
      disabled: "#64748b",
      inverse: "#07111f",
    },
    status: {
      success: "#34d399",
      warning: "#fbbf24",
      error: "#f87171",
      info: "#38bdf8",
    },
    border: {
      default: "rgba(148, 163, 184, 0.14)",
      strong: "rgba(148, 163, 184, 0.28)",
      focus: "#38bdf8",
    },
    common: {
      white: "#ffffff",
      black: "#000000",
      transparent: "transparent",
    },
    neutral: {
      dark: "#0f172a",
      darkMuted: "#475569",
      lightSurface: "#ffffff",
    },
    payment: {
      bitpay: "#0d47a1",
      zarinpal: "#f9a825",
      zibal: "#1b5e20",
    },
    visualization: {
      blue: "#42a5f5",
      royal: "#1565c0",
      teal: "#26a69a",
      tealDark: "#00897b",
      green: "#66bb6a",
      purple: "#ab47bc",
      amber: "#ffb300",
      orange: "#ffa726",
      red: "#ef5350",
    },
  },
  typography: {
    fontFamily: '"Vazirmatn", Tahoma, system-ui, sans-serif',
    size: {
      xs: "0.75rem",
      sm: "0.875rem",
      md: "0.9375rem",
      lg: "1.05rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.75rem",
    },
    weight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
    lineHeight: {
      tight: 1.35,
      title: 1.45,
      compact: 1.55,
      body: 1.7,
      relaxed: 1.85,
    },
  },
  spacing: {
    0: 0,
    "0.5": 4,
    1: 8,
    "1.5": 12,
    2: 16,
    "2.5": 20,
    3: 24,
    4: 32,
    5: 40,
    6: 48,
    8: 64,
    10: 80,
    12: 96,
  },
  radius: {
    none: 0,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    pill: 999,
    circle: "50%",
  },
  shadow: {
    none: "none",
    sm: "0 2px 10px rgba(0, 0, 0, 0.16)",
    md: "0 4px 28px rgba(0, 0, 0, 0.28)",
    lg: "0 12px 40px rgba(0, 0, 0, 0.36)",
    focus: "0 0 0 3px rgba(56, 189, 248, 0.28)",
  },
  control: {
    height: {
      small: 32,
      medium: 40,
      large: 48,
    },
    iconButton: {
      small: 32,
      medium: 40,
      large: 48,
    },
  },
  icon: {
    xs: 16,
    sm: 20,
    md: 24,
    lg: 32,
  },
  layout: {
    drawerWidth: 260,
    contentMaxWidth: 1600,
    readableMaxWidth: 760,
    pagePadding: {
      xs: 16,
      sm: 20,
      md: 24,
      lg: 28,
    },
    sectionGap: 32,
    headerGap: 24,
  },
  breakpoint: {
    xs: 0,
    sm: 600,
    md: 900,
    lg: 1200,
    xl: 1536,
  },
  zIndex: {
    appBar: 1100,
    drawer: 1200,
    modal: 1300,
    popover: 1400,
    tooltip: 1500,
    toast: 1600,
    datePicker: 1700,
  },
  motion: {
    duration: {
      shortest: 150,
      shorter: 200,
      short: 250,
      standard: 300,
      complex: 375,
    },
    easing: {
      easeInOut: "cubic-bezier(0.4, 0, 0.2, 1)",
      easeOut: "cubic-bezier(0.16, 1, 0.3, 1)",
      easeIn: "cubic-bezier(0.4, 0, 1, 1)",
      sharp: "cubic-bezier(0.4, 0, 0.6, 1)",
      spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
    },
  },
} as const;

export const cssDesignVariables = {
  "--ds-font-family": designTokens.typography.fontFamily,
  "--ds-color-brand-primary": designTokens.color.brand.primary,
  "--ds-color-brand-secondary": designTokens.color.brand.secondary,
  "--ds-color-bg-default": designTokens.color.background.default,
  "--ds-color-bg-surface": designTokens.color.background.surface,
  "--ds-color-bg-elevated": designTokens.color.background.elevated,
  "--ds-color-text-primary": designTokens.color.text.primary,
  "--ds-color-text-secondary": designTokens.color.text.secondary,
  "--ds-color-text-disabled": designTokens.color.text.disabled,
  "--ds-color-border": designTokens.color.border.default,
  "--ds-color-success": designTokens.color.status.success,
  "--ds-color-warning": designTokens.color.status.warning,
  "--ds-color-error": designTokens.color.status.error,
  "--ds-color-info": designTokens.color.status.info,
  "--ds-color-border-strong": designTokens.color.border.strong,
  "--ds-color-neutral-dark": designTokens.color.neutral.dark,
  "--ds-color-neutral-dark-muted": designTokens.color.neutral.darkMuted,
  "--ds-color-neutral-light-surface": designTokens.color.neutral.lightSurface,
  "--ds-chart-blue": designTokens.color.visualization.blue,
  "--ds-chart-royal": designTokens.color.visualization.royal,
  "--ds-chart-teal": designTokens.color.visualization.teal,
  "--ds-chart-teal-dark": designTokens.color.visualization.tealDark,
  "--ds-chart-green": designTokens.color.visualization.green,
  "--ds-chart-purple": designTokens.color.visualization.purple,
  "--ds-chart-amber": designTokens.color.visualization.amber,
  "--ds-chart-orange": designTokens.color.visualization.orange,
  "--ds-chart-red": designTokens.color.visualization.red,
  "--ds-font-size-body": designTokens.typography.size.md,
  "--ds-line-height-body": String(designTokens.typography.lineHeight.body),
  "--ds-font-weight-semibold": String(designTokens.typography.weight.semibold),
  "--ds-space-1": `${designTokens.spacing[1]}px`,
  "--ds-space-1-5": `${designTokens.spacing["1.5"]}px`,
  "--ds-space-2": `${designTokens.spacing[2]}px`,
  "--ds-space-3": `${designTokens.spacing[3]}px`,
  "--ds-space-4": `${designTokens.spacing[4]}px`,
  "--ds-radius-sm": `${designTokens.radius.sm}px`,
  "--ds-radius-md": `${designTokens.radius.md}px`,
  "--ds-radius-lg": `${designTokens.radius.lg}px`,
  "--ds-control-height-sm": `${designTokens.control.height.small}px`,
  "--ds-control-height-md": `${designTokens.control.height.medium}px`,
  "--ds-control-height-lg": `${designTokens.control.height.large}px`,
  "--ds-shadow-sm": designTokens.shadow.sm,
  "--ds-shadow-md": designTokens.shadow.md,
  "--ds-z-date-picker": String(designTokens.zIndex.datePicker),
  "--ds-ease-out": designTokens.motion.easing.easeOut,
  "--ds-ease-spring": designTokens.motion.easing.spring,
} as const;

export type DesignTokens = typeof designTokens;
